### ISSUE TITLE
Publish not trimming for -final packages

### ISSUE THREAD

**Issue by Tratcher** [aspnet/MetaPackages#161]
The -final .All package includes both versioned and final manifest files. E.g. aspnetcore-store-2.0.0-preview2-25756-linux-x64.xml and aspnetcore-store-2.0.0-preview2-final-linux-x64.xml.
The PublishWithAspNetCoreTargetManifest.targets file references the versioned manifests. These all reference versioned packages, which do not match the -final packages referenced by your app, so nothing gets trimmed.

@muratg @Eilon Preview2 blocking

**Comment by Eilon** [comment]
Moving to RTM milestone because we did the workaround for Preview2.

**Comment by JunTaoLuo** [comment]
This issue is masked in 2.0.0 by https://github.com/aspnet/MetaPackages/pull/143 which means even without any changes, trimming should work correctly for the -final package. However, we still need to fix this to remove the redundant manifests in the package. Also, this will break new builds of preview2. Note that the issue actually lies with the build scripts in Coherence-Signed, there won't be changes in this directory.

**Comment by JunTaoLuo** [comment]
The trimming issue has been fixed as part of https://github.com/aspnet/MetaPackages/pull/167 in preview2. The duplication is fixed by https://github.com/aspnet/Coherence-Signed/pull/588 in dev.
